#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
KR Market 라우트 헬퍼 호환 모듈

기존 import 호환성을 유지하기 위해 세부 helper 모듈을 재내보낸다.
"""

from app.routes.kr_market_backtest_helpers import (
    _aggregate_cumulative_kpis,
    _build_cumulative_trade_record,
    _build_latest_price_map,
    _build_ticker_price_index,
    _calculate_cumulative_trade_metrics,
    _calculate_jongga_backtest_stats,
    _calculate_scenario_return,
    _calculate_vcp_backtest_stats,
    _extract_stats_date_from_results_filename,
    _inject_latest_prices_to_candidates,
    _paginate_items,
    _prepare_cumulative_price_dataframe,
)
from app.routes.kr_market_signal_helpers import (
    _VALID_AI_ACTIONS,
    _apply_gemini_reanalysis_results,
    _apply_latest_prices_to_jongga_signals,
    _apply_vcp_reanalysis_updates,
    _build_ai_data_map,
    _build_ai_signal_from_jongga_signal,
    _build_ai_signals_from_jongga_results,
    _build_jongga_news_analysis_items,
    _build_normalized_gemini_result_map,
    _build_vcp_gemini_recommendation,
    _build_vcp_signal_from_row,
    _build_vcp_signals_from_dataframe,
    _build_vcp_stock_payload,
    _build_vcp_stock_payloads,
    _extract_jongga_ai_evaluation,
    _extract_jongga_score_value,
    _extract_vcp_ai_recommendation,
    _filter_signals_dataframe_by_date,
    _format_signal_date,
    _is_jongga_ai_analysis_completed,
    _is_meaningful_ai_reason,
    _is_vcp_ai_analysis_failed,
    _merge_ai_data_into_vcp_signals,
    _merge_legacy_ai_fields_into_map,
    _none_if_nan,
    _normalize_ai_payload_tickers,
    _normalize_jongga_signal_for_frontend,
    _normalize_jongga_signals_for_frontend,
    _normalize_text,
    _parse_datetime_safe,
    _recalculate_jongga_grade,
    _recalculate_jongga_grades,
    _safe_float,
    _safe_int,
    _select_signals_for_gemini_reanalysis,
    _should_use_jongga_ai_payload,
    _sort_and_limit_vcp_signals,
    _sort_jongga_signals,
)


__all__ = [
    "_VALID_AI_ACTIONS",
    "_aggregate_cumulative_kpis",
    "_apply_gemini_reanalysis_results",
    "_apply_latest_prices_to_jongga_signals",
    "_apply_vcp_reanalysis_updates",
    "_build_ai_data_map",
    "_build_ai_signal_from_jongga_signal",
    "_build_ai_signals_from_jongga_results",
    "_build_cumulative_trade_record",
    "_build_jongga_news_analysis_items",
    "_build_latest_price_map",
    "_build_normalized_gemini_result_map",
    "_build_ticker_price_index",
    "_build_vcp_gemini_recommendation",
    "_build_vcp_signal_from_row",
    "_build_vcp_signals_from_dataframe",
    "_build_vcp_stock_payload",
    "_build_vcp_stock_payloads",
    "_calculate_cumulative_trade_metrics",
    "_calculate_jongga_backtest_stats",
    "_calculate_scenario_return",
    "_calculate_vcp_backtest_stats",
    "_extract_jongga_ai_evaluation",
    "_extract_jongga_score_value",
    "_extract_stats_date_from_results_filename",
    "_extract_vcp_ai_recommendation",
    "_filter_signals_dataframe_by_date",
    "_format_signal_date",
    "_inject_latest_prices_to_candidates",
    "_is_jongga_ai_analysis_completed",
    "_is_meaningful_ai_reason",
    "_is_vcp_ai_analysis_failed",
    "_merge_ai_data_into_vcp_signals",
    "_merge_legacy_ai_fields_into_map",
    "_none_if_nan",
    "_normalize_ai_payload_tickers",
    "_normalize_jongga_signal_for_frontend",
    "_normalize_jongga_signals_for_frontend",
    "_normalize_text",
    "_paginate_items",
    "_parse_datetime_safe",
    "_prepare_cumulative_price_dataframe",
    "_recalculate_jongga_grade",
    "_recalculate_jongga_grades",
    "_safe_float",
    "_safe_int",
    "_select_signals_for_gemini_reanalysis",
    "_should_use_jongga_ai_payload",
    "_sort_and_limit_vcp_signals",
    "_sort_jongga_signals",
]
