#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
KR Market 라우트 시그널 헬퍼 (호환 re-export 레이어)

기존 import 경로를 유지하면서 구현을 도메인별 모듈로 분리한다.
"""

from app.routes.kr_market_jongga_signal_helpers import (
    _JONGGA_GRADE_PRIORITY,
    _apply_gemini_reanalysis_results,
    _apply_latest_prices_to_jongga_signals,
    _build_ai_signal_from_jongga_signal,
    _build_ai_signals_from_jongga_results,
    _build_jongga_news_analysis_items,
    _build_normalized_gemini_result_map,
    _extract_jongga_ai_evaluation,
    _extract_jongga_score_value,
    _is_jongga_ai_analysis_completed,
    _jongga_sort_key,
    _normalize_jongga_signal_for_frontend,
    _normalize_jongga_signals_for_frontend,
    _recalculate_jongga_grade,
    _recalculate_jongga_grades,
    _select_signals_for_gemini_reanalysis,
    _should_use_jongga_ai_payload,
    _sort_jongga_signals,
)
from app.routes.kr_market_signal_common import (
    _INVALID_AI_REASONS,
    _VALID_AI_ACTIONS,
    _format_signal_date,
    _is_meaningful_ai_reason,
    _none_if_nan,
    _normalize_ai_payload_tickers,
    _normalize_text,
    _parse_datetime_safe,
    _safe_float,
    _safe_int,
)
from app.routes.kr_market_vcp_signal_helpers import (
    _apply_vcp_reanalysis_updates,
    _build_ai_data_map,
    _build_vcp_gemini_recommendation,
    _build_vcp_signal_from_row,
    _build_vcp_signals_from_dataframe,
    _build_vcp_stock_payload,
    _build_vcp_stock_payloads,
    _extract_vcp_ai_recommendation,
    _filter_signals_dataframe_by_date,
    _is_vcp_ai_analysis_failed,
    _merge_ai_data_into_vcp_signals,
    _merge_legacy_ai_fields_into_map,
    _sort_and_limit_vcp_signals,
)

__all__ = [
    "_INVALID_AI_REASONS",
    "_JONGGA_GRADE_PRIORITY",
    "_VALID_AI_ACTIONS",
    "_apply_gemini_reanalysis_results",
    "_apply_latest_prices_to_jongga_signals",
    "_apply_vcp_reanalysis_updates",
    "_build_ai_data_map",
    "_build_ai_signal_from_jongga_signal",
    "_build_ai_signals_from_jongga_results",
    "_build_jongga_news_analysis_items",
    "_build_normalized_gemini_result_map",
    "_build_vcp_gemini_recommendation",
    "_build_vcp_signal_from_row",
    "_build_vcp_signals_from_dataframe",
    "_build_vcp_stock_payload",
    "_build_vcp_stock_payloads",
    "_extract_jongga_ai_evaluation",
    "_extract_jongga_score_value",
    "_extract_vcp_ai_recommendation",
    "_filter_signals_dataframe_by_date",
    "_format_signal_date",
    "_is_jongga_ai_analysis_completed",
    "_is_meaningful_ai_reason",
    "_is_vcp_ai_analysis_failed",
    "_jongga_sort_key",
    "_merge_ai_data_into_vcp_signals",
    "_merge_legacy_ai_fields_into_map",
    "_none_if_nan",
    "_normalize_ai_payload_tickers",
    "_normalize_jongga_signal_for_frontend",
    "_normalize_jongga_signals_for_frontend",
    "_normalize_text",
    "_parse_datetime_safe",
    "_recalculate_jongga_grade",
    "_recalculate_jongga_grades",
    "_safe_float",
    "_safe_int",
    "_select_signals_for_gemini_reanalysis",
    "_should_use_jongga_ai_payload",
    "_sort_and_limit_vcp_signals",
    "_sort_jongga_signals",
]
