#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
KR Market 라우트 의존성 맵 빌더
"""

from __future__ import annotations

from typing import Any, Callable


def build_market_data_route_deps(
    *,
    data_dir_getter: Callable[[], str],
    load_csv_file: Callable[[str], Any],
    load_json_file: Callable[[str], dict[str, Any]],
    get_data_path: Callable[[str], str],
    vcp_status: dict[str, Any],
    run_vcp_background_pipeline: Callable[..., None],
    start_vcp_screener_run: Callable[..., tuple[int, dict[str, Any]]],
    validate_vcp_reanalysis_source_frame: Callable[..., tuple[int, dict[str, Any] | None]],
    execute_vcp_failed_ai_reanalysis: Callable[..., tuple[int, dict[str, Any]]],
    update_vcp_ai_cache_files: Callable[[str, dict[str, Any], dict[str, Any] | None], int],
    build_market_status_payload: Callable[..., dict[str, Any]],
    build_vcp_signals_payload: Callable[..., dict[str, Any]],
    filter_signals_dataframe_by_date: Callable[..., Any],
    build_vcp_signals_from_dataframe: Callable[..., list[dict[str, Any]]],
    load_latest_vcp_price_map: Callable[[], dict[str, float]],
    apply_latest_prices_to_jongga_signals: Callable[..., int],
    sort_and_limit_vcp_signals: Callable[..., None],
    build_ai_data_map: Callable[..., dict[str, Any]],
    merge_legacy_ai_fields_into_map: Callable[..., None],
    merge_ai_data_into_vcp_signals: Callable[..., None],
    count_total_scanned_stocks: Callable[[str], int],
    build_stock_chart_payload: Callable[..., dict[str, Any]],
    resolve_chart_period_days: Callable[[str], int],
    build_ai_analysis_payload_for_target_date: Callable[..., dict[str, Any] | None],
    build_latest_ai_analysis_payload: Callable[..., dict[str, Any]],
    build_ai_signals_from_jongga_results: Callable[..., list[dict[str, Any]]],
    normalize_ai_payload_tickers: Callable[[dict[str, Any]], dict[str, Any]],
    format_signal_date: Callable[[Any], str],
    should_use_jongga_ai_payload: Callable[[Any, Any], bool],
    load_jongga_result_payloads: Callable[..., list[Any]],
    prepare_cumulative_price_dataframe: Callable[[Any], Any],
    build_ticker_price_index: Callable[[Any], dict[str, Any]],
    extract_stats_date_from_results_filename: Callable[..., str],
    build_cumulative_trade_record: Callable[..., dict[str, Any] | None],
    aggregate_cumulative_kpis: Callable[..., dict[str, Any]],
    paginate_items: Callable[..., tuple[list[Any], dict[str, Any]]],
    fetch_realtime_prices: Callable[..., dict[str, float]],
    build_jongga_latest_payload: Callable[..., dict[str, Any]],
    collect_jongga_v2_dates: Callable[..., list[str]],
    build_jongga_history_payload: Callable[..., tuple[int, dict[str, Any]]],
    recalculate_jongga_grades: Callable[[dict[str, Any]], bool],
    sort_jongga_signals: Callable[[list[dict[str, Any]]], None],
    normalize_jongga_signals_for_frontend: Callable[[list[dict[str, Any]]], None],
    build_backtest_summary_payload: Callable[..., dict[str, Any]],
    load_backtest_price_snapshot: Callable[[], tuple[Any, dict[str, Any]]],
    calculate_jongga_backtest_stats: Callable[..., dict[str, Any]],
    calculate_vcp_backtest_stats: Callable[..., dict[str, Any]],
    fetch_stock_detail_payload: Callable[..., dict[str, Any]],
) -> dict[str, Any]:
    return {
        "data_dir_getter": data_dir_getter,
        "load_csv_file": load_csv_file,
        "load_json_file": load_json_file,
        "get_data_path": get_data_path,
        "vcp_status": vcp_status,
        "run_vcp_background_pipeline": run_vcp_background_pipeline,
        "start_vcp_screener_run": start_vcp_screener_run,
        "validate_vcp_reanalysis_source_frame": validate_vcp_reanalysis_source_frame,
        "execute_vcp_failed_ai_reanalysis": execute_vcp_failed_ai_reanalysis,
        "update_vcp_ai_cache_files": update_vcp_ai_cache_files,
        "build_market_status_payload": build_market_status_payload,
        "build_vcp_signals_payload": build_vcp_signals_payload,
        "filter_signals_dataframe_by_date": filter_signals_dataframe_by_date,
        "build_vcp_signals_from_dataframe": build_vcp_signals_from_dataframe,
        "load_latest_vcp_price_map": load_latest_vcp_price_map,
        "apply_latest_prices_to_jongga_signals": apply_latest_prices_to_jongga_signals,
        "sort_and_limit_vcp_signals": sort_and_limit_vcp_signals,
        "build_ai_data_map": build_ai_data_map,
        "merge_legacy_ai_fields_into_map": merge_legacy_ai_fields_into_map,
        "merge_ai_data_into_vcp_signals": merge_ai_data_into_vcp_signals,
        "count_total_scanned_stocks": count_total_scanned_stocks,
        "build_stock_chart_payload": build_stock_chart_payload,
        "resolve_chart_period_days": resolve_chart_period_days,
        "build_ai_analysis_payload_for_target_date": build_ai_analysis_payload_for_target_date,
        "build_latest_ai_analysis_payload": build_latest_ai_analysis_payload,
        "build_ai_signals_from_jongga_results": build_ai_signals_from_jongga_results,
        "normalize_ai_payload_tickers": normalize_ai_payload_tickers,
        "format_signal_date": format_signal_date,
        "should_use_jongga_ai_payload": should_use_jongga_ai_payload,
        "load_jongga_result_payloads": load_jongga_result_payloads,
        "prepare_cumulative_price_dataframe": prepare_cumulative_price_dataframe,
        "build_ticker_price_index": build_ticker_price_index,
        "extract_stats_date_from_results_filename": extract_stats_date_from_results_filename,
        "build_cumulative_trade_record": build_cumulative_trade_record,
        "aggregate_cumulative_kpis": aggregate_cumulative_kpis,
        "paginate_items": paginate_items,
        "fetch_realtime_prices": fetch_realtime_prices,
        "build_jongga_latest_payload": build_jongga_latest_payload,
        "collect_jongga_v2_dates": collect_jongga_v2_dates,
        "build_jongga_history_payload": build_jongga_history_payload,
        "recalculate_jongga_grades": recalculate_jongga_grades,
        "sort_jongga_signals": sort_jongga_signals,
        "normalize_jongga_signals_for_frontend": normalize_jongga_signals_for_frontend,
        "build_backtest_summary_payload": build_backtest_summary_payload,
        "load_backtest_price_snapshot": load_backtest_price_snapshot,
        "calculate_jongga_backtest_stats": calculate_jongga_backtest_stats,
        "calculate_vcp_backtest_stats": calculate_vcp_backtest_stats,
        "fetch_stock_detail_payload": fetch_stock_detail_payload,
    }


def build_system_route_deps(
    *,
    resolve_market_gate_filename: Callable[[str | None], str],
    load_json_file: Callable[[str], dict[str, Any]],
    evaluate_market_gate_validity: Callable[..., tuple[bool, str, Any]],
    apply_market_gate_snapshot_fallback: Callable[..., dict[str, Any]],
    trigger_market_gate_background_refresh: Callable[[], None],
    build_market_gate_initializing_payload: Callable[..., dict[str, Any]],
    build_market_gate_empty_payload: Callable[..., dict[str, Any]],
    normalize_market_gate_payload: Callable[..., dict[str, Any]],
    execute_market_gate_update: Callable[..., tuple[int, dict[str, Any]]],
    execute_user_gemini_reanalysis_request: Callable[..., tuple[int, dict[str, Any]]],
    run_user_gemini_reanalysis: Callable[..., dict[str, Any]],
    project_root_getter: Callable[[], str],
    launch_background_update_job: Callable[..., tuple[bool, str]],
    launch_init_data_update: Callable[..., tuple[bool, str]],
    build_data_status_payload: Callable[..., dict[str, Any]],
    get_data_path: Callable[[str], str],
    load_csv_file: Callable[[str], Any],
) -> dict[str, Any]:
    return {
        "resolve_market_gate_filename": resolve_market_gate_filename,
        "load_json_file": load_json_file,
        "evaluate_market_gate_validity": evaluate_market_gate_validity,
        "apply_market_gate_snapshot_fallback": apply_market_gate_snapshot_fallback,
        "trigger_market_gate_background_refresh": trigger_market_gate_background_refresh,
        "build_market_gate_initializing_payload": build_market_gate_initializing_payload,
        "build_market_gate_empty_payload": build_market_gate_empty_payload,
        "normalize_market_gate_payload": normalize_market_gate_payload,
        "execute_market_gate_update": execute_market_gate_update,
        "execute_user_gemini_reanalysis_request": execute_user_gemini_reanalysis_request,
        "run_user_gemini_reanalysis": run_user_gemini_reanalysis,
        "project_root_getter": project_root_getter,
        "launch_background_update_job": launch_background_update_job,
        "launch_init_data_update": launch_init_data_update,
        "build_data_status_payload": build_data_status_payload,
        "get_data_path": get_data_path,
        "load_csv_file": load_csv_file,
    }


__all__ = [
    "build_market_data_route_deps",
    "build_system_route_deps",
]
